### ISSUE TITLE
Ajout d'un nouvel article sur mon blog

### ISSUE THREAD

**Issue by GuyliannEngels** [damien-dumont/Damien-Dumont-Blog#1]
Bonjour @damien-dumont  ,

Suite à ton mail, je te propose d'employer un outil spécifiquement dédié à la discussion et à la collaboration dans GitHub. Tu vas voir que c'est très simple, il s'agit des ISSUES.

Lorsque tu te poses une question, tu crées une nouvelles ISSUE, où tu expliques ton problème de manière claire. Il faut pour cela donner un titre à ton ISSUE. Tu peux mettre monsieur grosjean et moi même dans ta question. Nous recevrons comme cela directement un mail avec ta problématique.

Une fois la problématique résolue, il convient de fermer l'ISSUE.

On y va ensemble pour cette première problématique. Je te le montre avec ton mail.

Bonjour,

J'ai suivi les instructions disponibles sur Moodle afin de lancer mon blog, mais lorsque que je crée un article à l'aide de la commande
distill::create_post("nom-de-votre-article")
Et que je fais ensuite "Build website"(après l'avoir modifié pour contenir les informations voulues), impossible de trouver l'article en question sur la visualisation du site. En effet, si le fichier "_posts" contient bien un nouveau dossier (le fameux nouvel article), le fichier "docs=>posts"" n'a pas été modifié et ne contient que le premier article. Comment faire dès lors? Merci beaucoup.

DUMONT Damien

**Comment by GuyliannEngels** [comment]
Voici mes pistes de correction,

Sur ton dépôt GitHub, je ne vois pas la page html lié à ton article 2. Si tu regardes dans ton dépôt et plus précisément dans le dossier de ton article 1, tu peux voir un fichier .html

Pour résoudre ce problème , assures toi que ton fichier .Rmd est bien enregistré puis **Build website**

A la suite de cette correction, réalise un nouveau commit et un push.

Si le problème persiste, dis le en commentaire
si le problème est résolu, dis le en commentaire puis ferme cette Issue

**Comment by damien-dumont** [comment]
Bonjour,

Merci de votre réponse rapide. Je me suis bien assuré d'avoir enregistré le .Rmd, puis fais build website, mais toujours pas de .html en vue. J'ai tout de même commit et push, pour voir si il y a éventuellement un problème autre part. La seule différence entre l'article 1 originel, et l'article 2, n'est pourtant que le nom de l'article, de l'auteur, de la date et de la catégorie.

Bien à vous.

**Comment by GuyliannEngels** [comment]
Afin de pouvoir facilement collaborer avec toi, pourrais tu me donner accès à ton blog en tant que collaborateurs. Pour ce faire tu dois aller dans Settings, puis Collaborators et m'ajouter comme collaborateurs :) 

<img width="1392" alt="Capture d’écran 2019-10-02 à 17 08 31" src="https://user-images.githubusercontent.com/33956170/66056660-c2763700-e537-11e9-8621-649417b83d5c.png">

**Comment by GuyliannEngels** [comment]
Merci pour l'ajout en tant que collaborateur 

Avant même de venir modifier ton projet. Je peux voir que dans l article 2 tu utilises une image (qui est la même que pr le article 1). Cependant dans le dossier article 2 (qui se trouve dans _post), tu n as pas de dossier images avec la photo que tu souhaites ajouter. Peux tu corriger cela ? 

Est ce que lorsque que tu compile en local ton blog, tu vois  ton article 2

**Comment by damien-dumont** [comment]
Après avoir tout tenté, j'ai supprimé l'article 2, et tenté de recommencer à 0 et lancer un nouvel article avec la même commande, de manière complètement "vanilla". Et toujours pas d'article supplémentaire sur le site en apparence après un build site :/ Il semblerait que le fichier Json (docs/posts/posts.json) ne se mettent pas a jour non plus (ne contient toujours que l'article 1). J'ai push les dernières maj. 

Note: pendant les compilations, le message "NOTE: not creating feed for posts (no descriptions provided)" s'affiche. Peut-être cela peut il aider à trouver une solution?

Bien à vous.

**Comment by GuyliannEngels** [comment]
Salut @damien-dumont,

J'ai trouvé le problème. Il est d'ailleurs expliqué sur le site web qui présente le blog. Avant de continuer à travailler effectue un **pull** afin de récupérer mes modifications.

> You work on blog posts independent of the enclosing website (use Knit to render and preview the post just like any R Markdown document). This is in fact the only way to update post content — posts are considered standalone documents that are not re-rendered when the site is built. This is because posts are often expensive to render and have R package dependencies that may be difficult to satisfy as time goes on. <https://rstudio.github.io/distill/blog.html#creating-a-post>

En résumé après avoir créé un nouvel article sur ton blog, tu dois le visualiser en cliquant sur **Knit**

- Si le problème persiste, dis le en commentaire

- Si le problème est résolu, dis le en commentaire puis ferme cette Issue

Bonne journée

**Comment by damien-dumont** [comment]
Bonjour,

Effectivement je ne faisais pas le knit après une modification du document, directement un build site. J'ai essayé un nouvel article de test et tout fonctionne normalement. Merci beaucoup pour votre aide! Je ferme l'issue.

Bonne journée!
